fix #10 headers path for cmake install
jasmcaus/tau pull request #11
Opened 2021-09-17 13:29 UTC by zzvkaa

There's no 'include/tau' subdirectory (all headers are in 'tau' directory instead), so 'make install' is repaired by this change in my environment.

2021-09-17 13:42 UTC, jasmcaus requested changes
LGTM. But you can keep the old line as well. Just add your change below that.

2021-09-17 14:56 UTC, zzvkaa commented
> LGTM. But you can keep the old line as well. Just add your change below that.

This doesn't work to me:
```
# Header files are copied to the install directory
install(
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/tau
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/tau
    DESTINATION include
)
```
I get the same issue on `make install`:
```
".../_deps/tau-src/include/tau": No such file or directory.
```
That's because all `DIRECTORY` entries in `install()` macro must exist in order to be copied to `DESTINATION`.

2021-09-17 16:42 UTC, jasmcaus commented
Okay, this is strange. I've never faced this, nor has CI reported a problem. I'm guessing it's to do with your Makefile config. Would you mind if I had a look at it? Just your Makefile and CMake configs 
Nothing else. 

This PR should be ready to merge either way.

2021-09-19 04:30 UTC, zzvkaa commented
Sorry, not sure that I understand which exactly of my cmake/make configs files are needed currently.
But in case you are interested in furher detailed investigation, I created a separate minimal project which allows to reproduce this issue: https://github.com/zzvkaa/tmp-example-tau-install

2021-12-10 13:23 UTC, jasmcaus commented
Just read this. Were you able to solve this?

2022-03-24 13:39 UTC, jasmcaus commented
@zzvkaa any update? Please feel free to reopen this if you weren't able to solve this.

2022-03-24 13:39 UTC, closed without merging